### ISSUE TITLE
Almost impossible to copy and move files on Windows

### ISSUE THREAD

**Issue by gabriellluz** [mar10/wsgidav#149] opened 2019-03-25 00:47 UTC
I never really had problems using Wsidav on a linux environment.
The thing is: I'm now using Windows and since official Windows Webdav doesn't work, I stick to wsgidav. I can open files without problems from a wsgidav mount point, but I can't copy files to a wsgidav folder. I just can't. Sometimes it says "No space left" which is not true since I got 80gb free on both source and destination folders.

I have this problem on Windows since version 2.x.x. I thought it would change when I've updated, but the same thing happens.
I'm using it with auth=anonymous since I don't know how to use authentication on Windows.

**Comment by gabriellluz** [comment] 2019-03-25 16:27
Same problem using Android accessing a wsgidav folder.

**Comment by mar10** [comment] 2019-04-22 11:55
I assume you mean that you have problems when the WebDAV *client* is Windows based, such as the Mini-Redirector that is used by the `> net use ...` command?
Or does it make a difference on what OS the WsgiDAV server runs?

The mini.redirectors are known to have problems, sometimes they can be fixed by implementing a kind of quirks mode in the server behavior.

Could you give some more details, please:

- What OS windows Version are you using for client and server? Could you share the configuration?
- How do you connect to WebDAV (Access a mapped drive via commond line, use Fiel Explorer, ...)?
- Could you post a snippet of the WsgiDAV log in verbose mode, that shows the problem?
- Are you aware of another WebDAV server that works better, when you connect to that (so we can compare the access logs)

**Comment by gabriellluz** [comment] 2019-04-22 15:35
I had the same problem using an Android client (Smart File Manager and Astro File Manager) and using both Windows 7 and Windows 10.

**Comment by mar10** [comment] 2019-04-27 13:59
Some testing:
```
                Server:  Win 10      macOS
  Win File Explorer:     slow(1)     slow(1)
  Win 'net use w':       slow(1)     slow(1)
  Mac Finder:            fast(2)     fast(2)
```
  (1): Windows MiniRedir copies large files fast enough (a raw 6 MB PUT takes only 0.1 sec). 
       Deleting multiple files is also ok.
       **Problem**: copying many files seems to introduce some 1 second delays between single requests *per file*!

No matter if SSL is enabled or not.
No matter if authentication is used or not.
No matter if on Windows the ['Automatically detect settings' option is disabled](https://support.microsoft.com/en-us/help/2445570/slow-response-working-with-webdav-resources-on-windows-vista-or-window) or not.

This is a single copy sequence for 6MB file:

    14:45:13.110 - "PROPFIND /" length=0, depth=0, elap=0.000sec -> 207 Multi-Status
    < ... 1.0 second ...>
    14:45:12.079 - "PROPFIND /Foto 2 - Kopie (2).JPG" length=0, depth=0, elap=0.000sec -> 404 Not Found
    14:45:13.126 - "PUT /Foto 2 - Kopie (2).JPG" length=0, elap=0.016sec -> 201 Created
    < ... 1.0 second ...>
    14:45:14.157 - "LOCK /Foto 2 - Kopie (2).JPG" length=197, depth=infinity, elap=0.000sec -> 200 OK
    14:45:14.204 - "PROPPATCH /Foto 2 - Kopie (2).JPG" length=443, depth=0, elap=0.000sec -> 207 Multi-Status
    14:45:14.204 - "HEAD /Foto 2 - Kopie (2).JPG" elap=0.000sec -> 401 Not Authorized
    < ... 1.1 seconds ...>
    14:45:15.393 - "PUT /Foto 2 - Kopie (2).JPG" length=6122453, elap=0.156sec -> 204 No Content
    14:45:15.409 - "PROPPATCH /Foto 2 - Kopie (2).JPG" length=295, depth=0, elap=0.016sec -> 207 Multi-Status
    14:45:15.409 - "UNLOCK /Foto 2 - Kopie (2).JPG" elap=0.000sec -> 204 No Content

Other problems on Windows include:

- The network mapping seems to fail for unknown reasons sometimes when re-connecting etc.

**Comment by gabriellluz** [comment] 2019-04-29 10:47
Exactly. I don't have trouble using connecting to wsgidav on Ubuntu with rclone or whatever.

**Comment by SteffenDE** [comment] 2019-05-12 22:33
I really didn't expect that this is so easy, but the first result googling "windows 7 webdav performance issues" actually fixed this for me on Windows 7. Windows 10 works fine.
http://oddballupdate.com/2009/12/fix-slow-webdav-performance-in-windows-7/

I think this is definitely no wsgisav issue, as the same happens for me when connecting to a Nextcloud server.

**Comment by SteffenDE** [comment] 2019-05-12 23:25
Okay, I'm sorry. I didn't read the whole issue very carefully. I do not experience this issue as I'm not using the default Filesystem provider and cheroot but rather a custom implementation + Gevent. Using the default configuration, the Windows clients are **SLOW**.
Using Gevent fixes these issues for me:

```python
from gevent import monkey
monkey.patch_all()
from gevent.pywsgi import WSGIServer
from wsgidav.wsgidav_app import WsgiDAVApp

config = {
    "host": "0.0.0.0",
    "port": 8000,
    "provider_mapping": {
        "/": "/Users/Steffen"
    },
    "verbose": 1,
    "simple_dc": {
        "user_mapping": {
            "*": True
        }
    }
}

app = WsgiDAVApp(config)

http_server = WSGIServer(("", 8000), app)
http_server.serve_forever()
```

So: seems to be an issue with cheroot.

**Comment by SteffenDE** [comment] 2019-05-13 21:50
@gabriellluz It‘d be great if you could check if using `--server=gevent` fixes your performance issues.

**Comment by mar10** [comment] 2019-05-15 20:46
Some more information when running WsgiDAV on Windows 10 and accessing it with Fileexplorer from the same machine:

1. Run `wsgidav --host 0.0.0.0 --server ANY`, connect to `http://localhost:8080/`:
    File Explorer **is extremely slow** (1-3 seconds delay between every file operation) when connecting to 'localhost'
    No matter if: cheroot/gevent, SSL on/off, authenticated/anonymous
    I assume this is a problem with my person local Network or DNS configuration.
    E.g. using gevent:
    ![image](https://user-images.githubusercontent.com/41663/57806938-7bda9880-7760-11e9-8fb4-ccdc64c34f80.png)

1. Run `wsgidav --server gevent --host 0.0.0.0`, connect to `http://192.168.0.17:8080/`  
   Accessing using the IP address works fast with gevent:  
    ![image](https://user-images.githubusercontent.com/41663/57807242-0fac6480-7761-11e9-813a-218d09e44fea.png)

1. Run `wsgidav --server cheroot --host 0.0.0.0`, connect to `http://192.168.0.17:8080/`  
   Accessing using the IP address still slow with cheroot:  
![image](https://user-images.githubusercontent.com/41663/57807386-5b5f0e00-7761-11e9-8d08-51e730366b1d.png)

1. Run `wsgidav --server cheroot --host 0.0.0.0`, connect to `http://192.168.0.17:8080/`  
   Increasing thread count to 100 for cheroot improves it:  
![image](https://user-images.githubusercontent.com/41663/57807574-b8f35a80-7761-11e9-8124-d3653d7ff48e.png)

1. Run `wsgidav --server cheroot --host 0.0.0.0`, connect to `http://192.168.0.17:8080/`  
   Increasing cheroots thread count to 256 improves it even more:  
![image](https://user-images.githubusercontent.com/41663/57807701-fb1c9c00-7761-11e9-8001-8b7d63566a8d.png)

**Comment by mar10** [comment] 2019-05-15 20:59
I will increase the default thread count for cheroot in the next release, but it is also already configurable, for example in wsgidav.yaml:

```yaml
# ============================================================================
# SERVER OPTIONS

# server: "cheroot"
server_args:
    # File Explorer needs lot of threads (see #149):
    numthreads: 256
```

The next MSI installer should also include gevent.

**Comment by mar10** [comment] 2019-05-18 13:09
Increasing the number of threads for cheroot may be a workaround, but the root cause may be a problem that is currently addressed here: cherrypy/cheroot#91

**Comment by webknjaz** [comment] 2019-10-10 09:21
@mar10 Please test this with Cheroot v8.1.0

**Closed** 2019-10-12 11:03 UTC
Labels: client-miniredir, client-related, core

**Comment by mar10** [comment] 2019-10-12 11:04
@webknjaz Did only a smoke test, but it seems to be fixed. Thanks!
