### ISSUE TITLE
Bug: PermissionError causes ValueError: invalid literal for int() with base 10: ''

### ISSUE THREAD

**Issue by phillmac** [mar10/wsgidav#189] opened 2020-08-11 01:05 UTC
I have an ipfs share that is read only.
However if I try to create a file in this read only share, it gives an unexpected error in console.
The `PermissionError: [Errno 1] Operation not permitted: '/ipfs'` is perfectly normal, however the second error, `ValueError: invalid literal for int() with base 10: ''` seems to be bug?

```
Traceback (most recent call last):
  File "/home/phill/.local/lib/python3.8/site-packages/wsgidav/error_printer.py", line 52, in __call__
    for v in app_iter:
  File "/home/phill/.local/lib/python3.8/site-packages/wsgidav/request_resolver.py", line 213, in __call__
    for v in app_iter:
  File "/home/phill/.local/lib/python3.8/site-packages/wsgidav/request_server.py", line 126, in __call__
    app_iter = provider.custom_request_handler(environ, start_response, method)
  File "/home/phill/.local/lib/python3.8/site-packages/wsgidav/dav_provider.py", line 1525, in custom_request_handler
    return default_handler(environ, start_response)
  File "/home/phill/.local/lib/python3.8/site-packages/wsgidav/request_server.py", line 345, in do_PROPFIND
    reslist = res.get_descendants(depth=environ["HTTP_DEPTH"], add_self=True)
  File "/home/phill/.local/lib/python3.8/site-packages/wsgidav/dav_provider.py", line 461, in get_descendants
    for child in self.get_member_list():
  File "/home/phill/.local/lib/python3.8/site-packages/wsgidav/dav_provider.py", line 419, in get_member_list
    for name in self.get_member_names():
  File "/home/phill/.local/lib/python3.8/site-packages/wsgidav/fs_dav_provider.py", line 218, in get_member_names
    for name in os.listdir(self._file_path):
PermissionError: [Errno 1] Operation not permitted: '/ipfs'

ValueError("invalid literal for int() with base 10: ''")
Traceback (most recent call last):
  File "/home/phill/.local/lib/python3.8/site-packages/cheroot/wsgi.py", line 145, in respond
    for chunk in filter(None, response):
  File "/home/phill/.local/lib/python3.8/site-packages/wsgidav/wsgidav_app.py", line 563, in __call__
    for v in app_iter:
  File "/home/phill/.local/lib/python3.8/site-packages/wsgidav/debug_filter.py", line 157, in __call__
    for v in app_iter:
  File "/home/phill/.local/lib/python3.8/site-packages/wsgidav/error_printer.py", line 52, in __call__
    for v in app_iter:
  File "/home/phill/.local/lib/python3.8/site-packages/wsgidav/request_resolver.py", line 213, in __call__
    for v in app_iter:
  File "/home/phill/.local/lib/python3.8/site-packages/wsgidav/request_server.py", line 126, in __call__
    app_iter = provider.custom_request_handler(environ, start_response, method)
  File "/home/phill/.local/lib/python3.8/site-packages/wsgidav/dav_provider.py", line 1525, in custom_request_handler
    return default_handler(environ, start_response)
  File "/home/phill/.local/lib/python3.8/site-packages/wsgidav/request_server.py", line 345, in do_PROPFIND
    reslist = res.get_descendants(depth=environ["HTTP_DEPTH"], add_self=True)
  File "/home/phill/.local/lib/python3.8/site-packages/wsgidav/dav_provider.py", line 461, in get_descendants
    for child in self.get_member_list():
  File "/home/phill/.local/lib/python3.8/site-packages/wsgidav/dav_provider.py", line 419, in get_member_list
    for name in self.get_member_names():
  File "/home/phill/.local/lib/python3.8/site-packages/wsgidav/fs_dav_provider.py", line 218, in get_member_names
    for name in os.listdir(self._file_path):
PermissionError: [Errno 1] Operation not permitted: '/ipfs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/phill/.local/lib/python3.8/site-packages/cheroot/server.py", line 1277, in communicate
    req.respond()
  File "/home/phill/.local/lib/python3.8/site-packages/cheroot/server.py", line 1073, in respond
    self.server.gateway(self).respond()
  File "/home/phill/.local/lib/python3.8/site-packages/cheroot/wsgi.py", line 151, in respond
    self.req.ensure_headers_sent()
  File "/home/phill/.local/lib/python3.8/site-packages/cheroot/server.py", line 1120, in ensure_headers_sent
    self.send_headers()
  File "/home/phill/.local/lib/python3.8/site-packages/cheroot/server.py", line 1138, in send_headers
    status = int(self.status[:3])
ValueError: invalid literal for int() with base 10: ''
```

**Comment by mar10** [comment] 2020-08-23 18:42
I couldn't reproduce it here with

    Running WsgiDAV/3.0.4 Cheroot/8.4.2 Python/3.7.7

I can mock an exception, but I don't get the `ValueError: invalid literal for int() with base 10: ''` error in `send_headers`

Could you add some more info?

**Comment by phillmac** [comment] 2020-08-24 01:13
I was mistaken that creating a file is the trigger, it's a little more complicated than what I first thought.

The upshot is this:

`/ipfs/` is a filesystem that follows these rules: 
 1. The file system is mounted read-write but any write operations will result in a permission error
 2. The next sub-level in the path **must** be a CID hash e.g. `/ipfs/QmVFrvcv6ZapvBsLUuUKEKegKpGG1ojKz8xva6HC9DVfJN`
3. This is a virtual file system, as such it has **no** children until a valid (matching rule # 2) child is requested, as such `ls /ipfs` results in a permission error 

As you see in the attached log in the gist, the windows client trying to access `/AutoRun.inf ` at the base of the share which translates to `/ipfs/AutoRun.inf ` on this linux host throws a permission error because it violates rule # 2
Also sometimes the windows client attempts to list the root of the share `/` translating to `/ipfs` violating rule # 3
This is the expected behaviour. What is unexpected is the secondary header error that's (*sometimes*) triggered following the permission error.

I can't seem to reproduce this secondary error in the logs this time.

Config & logs are here: https://gist.github.com/phillmac/926080a445caa6af93001fe7730922fc
`/ipfs` and `/ipns` are read-write fuse mounted filesystems as per `findmnt ` and mounted by the same user wsgidav is running under :
```
├─/ipfs                               /dev/fuse                         fuse        rw,nosuid,nodev,relatime,user_id=1000,group_id=1000
└─/ipns                               /dev/fuse                         fuse        rw,nosuid,nodev,relatime,user_id=1000,group_id=1000
```

Hopefully this should help to nail down the lifecycle of the bug a bit better, if you need more details, let me know :D

**Comment by phillmac** [comment] 2020-08-24 02:33
Managed to get a clean trace with debug enabled, showing the full error.
[wsgidav-error2.log](https://github.com/mar10/wsgidav/files/5115477/wsgidav-error2.log)

**Comment by phillmac** [comment] 2020-08-24 02:39
Confirmed it with a browser... trying to open the root of the `/ipfs` share triggers the bug 100% of the time

**Comment by mar10** [comment] 2020-08-25 19:46
Thanks for providing the details.
It seems to be related to the processing in the error_printer middleware. 
It could use some refactoring, but you can try this setting as a workaround:
```yaml
error_printer:
    catch_all: true
```
(Which should be default btw. Did you explicitly set it to false before?)

**Comment by phillmac** [comment] 2020-08-25 20:26
Nope. I grabbed a copy of the example config as a template, set up my shares and left everything else alone.

**Comment by mar10** [comment] 2020-08-25 20:40
I updated the sample. Does setting `true` help in your case?

**Comment by phillmac** [comment] 2020-08-28 23:34
Yup, that seems to at least mitigate the problem, I get a clean 500 error and the stack trace now looks something like this:
```
23:31:33.931 - <139958434023168> wsgidav.error_printer       ERROR   : Traceback (most recent call last):
  File "/home/phill/.local/lib/python3.8/site-packages/wsgidav/error_printer.py", line 51, in __call__
    app_iter = self.next_app(environ, sub_app_start_response)
  File "/home/phill/.local/lib/python3.8/site-packages/wsgidav/http_authenticator.py", line 223, in __call__
    return self.next_app(environ, start_response)
  File "/home/phill/.local/lib/python3.8/site-packages/wsgidav/dir_browser/_dir_browser.py", line 110, in __call__
    context = self._get_context(environ, dav_res)
  File "/home/phill/.local/lib/python3.8/site-packages/wsgidav/dir_browser/_dir_browser.py", line 182, in _get_context
    childList = dav_res.get_descendants(depth="1", add_self=False)
  File "/home/phill/.local/lib/python3.8/site-packages/wsgidav/dav_provider.py", line 461, in get_descendants
    for child in self.get_member_list():
  File "/home/phill/.local/lib/python3.8/site-packages/wsgidav/dav_provider.py", line 419, in get_member_list
    for name in self.get_member_names():
  File "/home/phill/.local/lib/python3.8/site-packages/wsgidav/fs_dav_provider.py", line 218, in get_member_names
    for name in os.listdir(self._file_path):
PermissionError: [Errno 1] Operation not permitted: '/ipfs'

23:31:33.932 - <139958434023168> wsgidav.error_printer       ERROR   : Caught HTTPRequestException(HTTP_INTERNAL_ERROR)
Traceback (most recent call last):
  File "/home/phill/.local/lib/python3.8/site-packages/wsgidav/error_printer.py", line 51, in __call__
    app_iter = self.next_app(environ, sub_app_start_response)
  File "/home/phill/.local/lib/python3.8/site-packages/wsgidav/http_authenticator.py", line 223, in __call__
    return self.next_app(environ, start_response)
  File "/home/phill/.local/lib/python3.8/site-packages/wsgidav/dir_browser/_dir_browser.py", line 110, in __call__
    context = self._get_context(environ, dav_res)
  File "/home/phill/.local/lib/python3.8/site-packages/wsgidav/dir_browser/_dir_browser.py", line 182, in _get_context
    childList = dav_res.get_descendants(depth="1", add_self=False)
  File "/home/phill/.local/lib/python3.8/site-packages/wsgidav/dav_provider.py", line 461, in get_descendants
    for child in self.get_member_list():
  File "/home/phill/.local/lib/python3.8/site-packages/wsgidav/dav_provider.py", line 419, in get_member_list
    for name in self.get_member_names():
  File "/home/phill/.local/lib/python3.8/site-packages/wsgidav/fs_dav_provider.py", line 218, in get_member_names
    for name in os.listdir(self._file_path):
PermissionError: [Errno 1] Operation not permitted: '/ipfs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/phill/.local/lib/python3.8/site-packages/wsgidav/error_printer.py", line 88, in __call__
    raise as_DAVError(e)
wsgidav.dav_error.DAVError: DAVError(500 Internal Server Error: An internal server error occurred
    Source exception: '[Errno 1] Operation not permitted: '/ipfs'')

23:31:33.932 - <139958434023168> wsgidav.error_printer       ERROR   : e.src_exception:
[Errno 1] Operation not permitted: '/ipfs'
```

**Comment by mar10** [comment] 2020-09-27 17:20
Closing this bug for now, but improved the error handling in the middleware stack should be addressed in the next major release.
Especially the error_printer could need a review.

**Closed by mar10** 2020-09-27 17:20 UTC
Labels: bug, fs-provider
